name: Update Changelog On Pull Request

on:
  pull_request:
    types: [opened, synchronized, edited]
    branches:
      - main

jobs:
  mark_changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "auto-commit PR description to changelog"
        run: chmod +x ./update-changelog.sh && ./update-changelog.sh

